### PR TITLE
fix: don't extract the first element from vectors

### PR DESCRIPTION
**Pull request by satra**
this PR attempts to fix the multiple choice selection issue that @ibevers faced.

i'm going to leave this as draft. 

@ibevers - you'll need to add a github workflow and config in your repo like the nimh-minimal protocol to be able to use this committish for your UI.

### CODE REVIEW

**Comment by satra** [comment]
i'm not sure what the piece of code that i changed is doing, hence i need to study the implications a bit. in the meantime, this did not seem to break things (on initial eval).

**Comment by fabiocat93** [comment]
Hi @satra, here is my 2 cents. From what I understand, your recent changes help with dropdowns and checkboxes accepting multiple options, but I encountered a new issue. When saving the response to this form:
Screenshot 2024-08-07 at 11 55 50 AM
The expected output should be:
```json
"value": {
    "first_name": "a",
    "middle_name": "b",
    "last_name": "ccccc"
}
```
However, the actual output is:
```json
"value": {
    "first_name": "a"
}
```
This is my first time touching the code of `rephoschema` and I don't have a bigger picture of the code, but it seems that removing the if block entirely it resolves the problem without introducing new issues. Here's the block I'm referring to:
```node
if (_.isObject(val) && !_.isArray(val) && !val.hasOwnProperty('unitCode') && !(val instanceof Blob)) {
    const sectionItemKey = Object.keys(val)[0];
    const sectionItemValue = Object.values(val)[0];
    exportVal = sectionItemValue;
    usedList.push(sectionItemKey);
    isAboutUrl = sectionItemKey;
}
```

**Comment by satra** [comment]
thanks @fabiocat93 - i think we have arrived at the same conclusion for now.

**Comment by satra** [comment]
and the example you shared provides a clue to what should perhaps replace that block. i'll take a look. thank you.

**Comment by satra** [comment]
closing in favor of #335

**Pull request closed without merging**
