### PR TITLE
[Draft] Temporary fix for Yibei's schema -- issues with Radio button component

### PR DESCRIPTION
**Pull request by aaronkanzer**
Cc @yibeichan

### CODE REVIEW

**Comment by satra** [comment]
is this fix still relevant?

**Comment by yibeichan** [comment]
this was for the between activity branching part, which didn't work as we hoped.

**Comment by satra** [comment]
can you clarify? this doesn't look like changes in the place where i enabled scoped variables. was it trying to address the same issue (e.g., age dependent branching in nimh-minimal)?

**Comment by yibeichan** [comment]
yes, @aaronkanzer made it to help with the same issue (age condition), but I'm not sure about the detailed changes made here.

**Comment by satra** [comment]
in that case, i'm going to close this, as we have addressed that more specifically with scoped variables.

**Pull request closed without merging**
