### PR TITLE
Fixes for running b2aiprotocol

### PR DESCRIPTION
**Pull request by ibevers**

### CODE REVIEW

**Comment by ibevers** [comment]
I ran into a challenge similar to the one with the race item before, where the first element of arrays was getting extracted. Jordan and I came up with this fix for it yesterday. It might have unintended side-effects, but so far, it doesn't seem to.

**Comment by satra** [comment]
can you create an example in demo-protocol to illustrate the issue? mostly because i thought this was no longer an issue. so there must a case where this still happens.

**Comment by ibevers** [comment]
Yes, it only seems to show up with nested activities. Since this fix unblocks me on interactively validating the mood protocol, I'm going to prioritize that over making a minimal example and giving a long explanation of the reasoning for this fix, but I will loop back to this.

**Comment by satra** [comment]
i'm closing this as this should have been fixed (and upgraded) in the PR that was merged #343

**Pull request closed without merging**
